# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ASUS-PC/Desktop/temporary/AXI_Stream/AXI_Stream_test/AXI_Stream_test.srcs/sources_1/bd/system/ip/system_axis_data_fifo_0_2/system_axis_data_fifo_0_2.xci
# IP: The module: 'system_axis_data_fifo_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ASUS-PC/Desktop/temporary/AXI_Stream/AXI_Stream_test/AXI_Stream_test.gen/sources_1/bd/system/ip/system_axis_data_fifo_0_2/system_axis_data_fifo_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axis_data_fifo_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/ASUS-PC/Desktop/temporary/AXI_Stream/AXI_Stream_test/AXI_Stream_test.srcs/sources_1/bd/system/ip/system_axis_data_fifo_0_2/system_axis_data_fifo_0_2.xci
# IP: The module: 'system_axis_data_fifo_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ASUS-PC/Desktop/temporary/AXI_Stream/AXI_Stream_test/AXI_Stream_test.gen/sources_1/bd/system/ip/system_axis_data_fifo_0_2/system_axis_data_fifo_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axis_data_fifo_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
